name: Testing - Reusable Workflow
on: 
  workflow_call: 
    inputs:
        ingress-url:
            required: true
            type: string
            description: 'Provide the Ingress URL'
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - env:
          URL: '${{ inputs.ingress-url }}'
        run: |
          echo "https://$URL/live"