name: Testing Docker Image

on: 
    workflow_call: 
        inputs:
            image_name:
                required: true
                type: string
jobs:
    testing_docker:
        runs-on: [ubuntu-latest]
        services:
            my-image:
                image: ${{ inputs.image_name }}
                ports:
                    - 3000:3000
                
        steps:
            - name: Testing Image
              run: curl http://my-image:3000tes